package mhyhre.lightrabbit.game.levels.events;

public enum EventType {

    NONE,

    UNIT_ADD, UNIT_KILL, UNIT_REMOVE, UNIT_HEALTH, UNIT_SPEED,
    UNIT_SET_IDEOLOGY, UNIT_SET_STOP_POSITION, PLAYER_SET_POSITION,
    
    NPC_CHANGE_STATE,

    MSSG_SHOW,
    
    STOP_TIME, STOP_TIME_IN, START_TIME, SET_TIME, SET_TIME_SPEED,

    SET_WATER_LEVEL,
    SET_WAVE_HEIGHT, 
    SET_WEATHER,
    
    SET_DIE_POSITION,
    
    SET_FOG_VISIBLE,
    
    WAIT_SECONDS, 
    WAIT_ENEMIES_EXIST,
    WAIT_FOREVER,
    
    WAIT_WHILE_UNIT_AGENTS_ACTIVE,
    
}