package mhyhre.lightrabbit.game.Levels;

public enum EventType {

    NONE,

    UNIT_ADD, UNIT_KILL, UNIT_REMOVE, UNIT_HEALTH, UNIT_SPEED,

    MSSG_SHOW,
    
    STOP_TIME, STOP_TIME_IN, START_TIME, SET_TIME, SET_TIME_SPEED,

    GAME_WATER_LEVEL, GAME_WAVE_HEIGHT, 
    GAME_TIME, 
    GAME_WEATHER, 
    
    GAME_SHOW_FOG, GAME_SET_FOG_VALUE,
    
    WAIT_SECONDS, 
    WAIT_ENEMIES_EXIST,
    WAIT_ALWAYS;
}