package mhyhre.lightrabbit.game.Levels;

public enum EventType {

    NONE,

    UNIT_ADD, UNIT_KILL, UNIT_REMOVE, UNIT_HEALTH, UNIT_SPEED,

    MSSG_SHOW,

    GAME_WATER_LEVEL, GAME_WAVE_HEIGHT, GAME_STOP_TIME, GAME_START_TIME, GAME_TIME, GAME_WEATHER, GAME_SHOW_FOG, GAME_WAIT_SECONDS, GAME_WAIT_ENEMIES_EXIST;
}