/*
 * Copyright (C) 2013-2015 Andrey Tulyakov
 * @mail: mhyhre@gmail.com
 */

package mhyhre.lightrabbit.game.levels.events;

public enum EventType {

    NONE,

    UNIT_ADD, UNIT_KILL, UNIT_REMOVE, UNIT_HEALTH, UNIT_SPEED,
    UNIT_SET_IDEOLOGY, UNIT_SET_POSITION, UNIT_SET_VPOSITION,
    UNIT_SET_GUN, UNIT_SET_PROJECTILES_COUNT,
    
    // AGENTS:
    UNIT_SET_STOP_POSITION, UNIT_SET_FIRE_POSITION, UNIT_SET_DIE_POSITION,
    
    NPC_CHANGE_STATE,

    SHOW_DIALOG,
    SHOW_TITLES,
    
    HIDE_TOP_PANEL, SHOW_TOP_PANEL,
    GUI_HIDE_ALL_ELEMENTS, GUI_SHOW_ELEMENT, GUI_HIDE_ELEMENT, GUI_BLINK_ELEMENT,

    STOP_TIME, STOP_TIME_IN, START_TIME, SET_TIME, SET_TIME_SPEED,

    SET_WATER_LEVEL,
    SET_WATER_WAVE_HEIGHT,
    SET_WATER_WAVE_REPEATING,
    SET_WATER_COLOR,
    
    SET_WEATHER,
    
    SET_DIE_POSITION,
    
    SET_FOG_VISIBLE,
    ENABLE_RAIN, DISABLE_RAIN,
    ENABLE_CLOUDS, DISABLE_CLOUDS,
    SKY_SET_PALETTE,
    

    
    WAIT_SECONDS, 
    WAIT_ENEMIES_EXIST,
    WAIT_FOREVER,
    WAIT_WHILE_OTHER_UNITS_EXIST,
    WAIT_WHILE_UNIT_AGENTS_ACTIVE,
    WAIT_WHILE_UNIT_ALIVE,
    
    MAKE_LIGHTNING,
    UNLOCK_LEVEL,
    SET_GAME_OVER_CONTIDION,
    END_GAME, 
}